### ISSUE TITLE
KeyError:'model' 

### ISSUE THREAD

**Issue by yiichu03** [Ma-Lab-Berkeley/CRATE#5]
when i run finetune.py ,i met a problem:
command is

python finetune.py --bs 256 --net CRATE_small
 --opt adamW --lr 5e-5 --n_epochs 200 --randomaug 1 --data cifar10 --ckpt_dir checkpoint.pth.tar --data_dir cifar-10

Error is

 File "D:\dachuang\CRATE\CRATE-main\finetune.py", line 99, in <module>
    net.load_state_dict(torch.load(args.ckpt_dir)['model'])
KeyError: 'model'

i wanna to know how to solve this question.
Thanks !

**Comment by BiEchi** [comment]
I believe we should preprocess the downloaded file like this first:

```python
import torch
ckpt = torch.load('./checkpoint.pth.tar')

ckpt['state_dict'].keys()
# remove 'module.' from keys
new_state_dict = {}
for k, v in ckpt['state_dict'].items():
    name = k[7:] # remove 'module.' from key
    new_state_dict[name] = v
ckpt['state_dict'] = new_state_dict
torch.save(ckpt, './checkpoint.pth.tar')
```

Then in `finetune.py`, we change the code like this:

```python
net.load_state_dict(torch.load(args.ckpt_dir)['state_dict']) #['model'])
```

Results will be like this:

<img width="895" alt="image" src="https://github.com/Ma-Lab-Berkeley/CRATE/assets/60613238/8f0a3739-1382-4945-ab7d-8ebb1ae9a186">

As this is simply an expedient, I'm pointing to @yaodongyu for a deep dive into this issue. This might be caused because the uploaded checkpoint is exported with a different interface to how the original project generated the checkpoint.

**Comment by LeslieTrue** [comment]
Hi all,
Thank you for reporting the error that is caused by the mismatched key from the original repo and the newly pretrained checkpoints. 
I have fixed it in current version~
